/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rpg_test;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void runUI() {

        uiPrinter.pc_chara_create();
        uiPrinter.pc_Commands();
       
    }

    public static void main(String[] args) {

       runUI();
        
        //System.out.println(new App().getGreeting());
    }
}
